### ISSUE TITLE
Unable to program 

### ISSUE THREAD

**Issue by Jugulaire** [raspitv/raspio_duino#3]
Hi, 

When i try to program my board with Arduino IDE i get a message saying "gpio:permission denied"
Can you help me ?

**Comment by raspitv** [comment]
Without knowing the specifics of your setup, here's a few general possibilities.

Have you set the fuses on your ATMEGA using avrsetup?
Which version of arduino IDE are you using (the one from apt-get or a direct download)?
Are you using Gordon Henderson's adjustments to the avrdude?
Did you set the two settings in tools menu (board and programmer)?
Are you trying to use "upload with programmer" rather than upload?
Have you got the programming jumpers in place?

Those are the most common issues.  you follow the instructions in the manual to the letter on a fresh SD card it will work.

**Comment by Jugulaire** [comment]
Hi,
Finally i got solution.
I need to change my user permission to use GPIO as normal user instead of root user.
Thank a lot, It's fun to program on this tiny board !
